export LIBPNG_VERSION="1.5.14"
export IMAGE_MAGICK_VERSION="6.8.7-5"
export REMOTE_PATH="imagemagick-${IMAGE_MAGICK_VERSION}.tgz"
export LIBPNG_REMOTE_PATH="libpng-${LIBPNG_VERSION}.tgz"
export S3_BUCKET="kc-buildpack-imagemagick"
